### ISSUE TITLE
5.0.1 The JSON value could not be converted to System.Int32

### ISSUE THREAD

**Issue by EpicKnarvik97** [jellyfin/jellyfin-ffmpeg#138]
**Describe The Bug**
After upgrading from jellyfin-ffmpeg:amd64 4.4.1-4-bullseye to 5.0.1-2-bullseye, I've had a lot of problems with newly added media. Files either cannot be played, or their duration changes by the second and all possible bitrates and resolutions can be chosen. Info about audio and subtitle tracks is also missing. The log displays `System.Text.Json.JsonException: The JSON value could not be converted to System.Int32.` which might be relevant (see log section). All affected video files have been ripped using MakeMKV.

**Steps To Reproduce**

1. Update jellyfin-ffmpeg to the newest version
2. Add a new video file to a library
3. Update library metadata
4. Try to play the new video

**Expected Behavior**

The video should display metadata such as resolution, audio tracks and subtitle tracks and play as expected.

**System (please complete the following information):**

- **Platform:** Linux
- **Operating System:** Debian 11
- **Virtualization**: None
- **Jellyfin Version:** 10.7.7-1
- **Jellyfin-FFmpeg Version:** 5.0.1-2-bullseye
- **Hardware Acceleration:** None
- **CPU & GPU Model**: 16 x AMD Ryzen 7 5700G with Radeon Graphics

**MediaInfo**

```ffprobe Askeladden\ og\ de\ gode\ hjelperne\ \(1961\).mkv 
ffprobe version 4.3.4-0+deb11u1 Copyright (c) 2007-2021 the FFmpeg developers
  built with gcc 10 (Debian 10.2.1-6)
  configuration: --prefix=/usr --extra-version=0+deb11u1 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl --disable-stripping --enable-avresample --disable-filter=resample --enable-gnutls --enable-ladspa --enable-libaom --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librabbitmq --enable-librsvg --enable-librubberband --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvidstab --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl --enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 51.100 / 56. 51.100
  libavcodec     58. 91.100 / 58. 91.100
  libavformat    58. 45.100 / 58. 45.100
  libavdevice    58. 10.100 / 58. 10.100
  libavfilter     7. 85.100 /  7. 85.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  7.100 /  5.  7.100
  libswresample   3.  7.100 /  3.  7.100
  libpostproc    55.  7.100 / 55.  7.100
Input #0, matroska,webm, from 'Askeladden og de gode hjelperne (1961).mkv':
  Metadata:
    encoder         : libmakemkv v1.16.7 (1.3.10/1.5.2) win(x64-release)
    creation_time   : 2022-05-04T10:33:27.000000Z
  Duration: 00:15:13.40, start: 0.000000, bitrate: 7224 kb/s
    Chapter #0:0: start 0.000000, end 29.640000
    Metadata:
      title           : Kapittel 01
    Chapter #0:1: start 29.640000, end 198.120000
    Metadata:
      title           : Kapittel 02
    Chapter #0:2: start 198.120000, end 429.520000
    Metadata:
      title           : Kapittel 03
    Chapter #0:3: start 429.520000, end 570.960000
    Metadata:
      title           : Kapittel 04
    Chapter #0:4: start 570.960000, end 812.240000
    Metadata:
      title           : Kapittel 05
    Chapter #0:5: start 812.240000, end 913.400000
    Metadata:
      title           : Kapittel 06
    Stream #0:0(eng): Video: mpeg2video (Main), yuv420p(tv, bt470bg, top first), 720x576 [SAR 64:45 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 50 tbc
    Metadata:
      BPS-eng         : 5473628
      DURATION-eng    : 00:15:13.400000000
      NUMBER_OF_FRAMES-eng: 22835
      NUMBER_OF_BYTES-eng: 624951534
      SOURCE_ID-eng   : 0100E0
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.16.7 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-05-04 10:33:27
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Side data:
      cpb: bitrate max/min/avg: 7500000/0/0 buffer size: 1835008 vbv_delay: N/A
    Stream #0:1(dan): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s (default)
    Metadata:
      title           : Surround 5.1
      BPS-eng         : 448000
      DURATION-eng    : 00:15:13.312000000
      NUMBER_OF_FRAMES-eng: 28541
      NUMBER_OF_BYTES-eng: 51145472
      SOURCE_ID-eng   : 0180BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.16.7 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-05-04 10:33:27
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:2(swe): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s
    Metadata:
      title           : Surround 5.1
      BPS-eng         : 448000
      DURATION-eng    : 00:15:13.312000000
      NUMBER_OF_FRAMES-eng: 28541
      NUMBER_OF_BYTES-eng: 51145472
      SOURCE_ID-eng   : 0181BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.16.7 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-05-04 10:33:27
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:3(nor): Audio: ac3, 48000 Hz, 5.1(side), fltp, 448 kb/s
    Metadata:
      title           : Surround 5.1
      BPS-eng         : 448000
      DURATION-eng    : 00:15:13.312000000
      NUMBER_OF_FRAMES-eng: 28541
      NUMBER_OF_BYTES-eng: 51145472
      SOURCE_ID-eng   : 0182BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.16.7 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-05-04 10:33:27
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:4(nor): Audio: ac3, 48000 Hz, stereo, fltp, 384 kb/s
    Metadata:
      title           : Stereo
      BPS-eng         : 384000
      DURATION-eng    : 00:15:13.312000000
      NUMBER_OF_FRAMES-eng: 28541
      NUMBER_OF_BYTES-eng: 43838976
      SOURCE_ID-eng   : 0183BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.16.7 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-05-04 10:33:27
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:5(nor): Subtitle: dvd_subtitle, 720x576 (default)
    Metadata:
      BPS-eng         : 5698
      DURATION-eng    : 00:14:11.957333333
      NUMBER_OF_FRAMES-eng: 139
      NUMBER_OF_BYTES-eng: 606850
      SOURCE_ID-eng   : 0120BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.16.7 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-05-04 10:33:27
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:6(nor): Subtitle: dvd_subtitle, 720x576
    Metadata:
      BPS-eng         : 4556
      DURATION-eng    : 00:14:16.234844444
      NUMBER_OF_FRAMES-eng: 112
      NUMBER_OF_BYTES-eng: 487706
      SOURCE_ID-eng   : 0122BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.16.7 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-05-04 10:33:27
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:7(eng): Subtitle: dvd_subtitle, 720x576
    Metadata:
      BPS-eng         : 5762
      DURATION-eng    : 00:15:05.952355555
      NUMBER_OF_FRAMES-eng: 143
      NUMBER_OF_BYTES-eng: 652606
      SOURCE_ID-eng   : 0124BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.16.7 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-05-04 10:33:27
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
    Stream #0:8(eng): Subtitle: dvd_subtitle, 720x576
    Metadata:
      BPS-eng         : 26954
      DURATION-eng    : 00:00:00.352711111
      NUMBER_OF_FRAMES-eng: 1
      NUMBER_OF_BYTES-eng: 1186
      SOURCE_ID-eng   : 0126BD
      _STATISTICS_WRITING_APP-eng: MakeMKV v1.16.7 win(x64-release)
      _STATISTICS_WRITING_DATE_UTC-eng: 2022-05-04 10:33:27
      _STATISTICS_TAGS-eng: BPS DURATION NUMBER_OF_FRAMES NUMBER_OF_BYTES SOURCE_ID
```

**FFmpeg Logs**

```[2022-05-04 15:19:42.682 +02:00] [INF] /usr/lib/jellyfin-ffmpeg/ffmpeg -f matroska -i file:"/media/kristian/Games/Movies/Ripped/Askeladden og de gode hjelperne (1961).mkv" -map_metadata -1 -map_chapters -1 -threads 0 -sn   -copyts -avoid_negative_ts disabled -max_muxing_queue_size 2048 -f hls -max_delay 5000000 -hls_time 3 -hls_segment_type mpegts -start_number 0 -hls_base_url "hls/a35fad927ac7e0e5fea764a10a16ea97/" -hls_playlist_type event -hls_segment_filename "/var/lib/jellyfin/transcodes/a35fad927ac7e0e5fea764a10a16ea97%d.ts" -y "/var/lib/jellyfin/transcodes/a35fad927ac7e0e5fea764a10a16ea97.m3u8"
[2022-05-04 15:19:45.594 +02:00] [WRN] Slow HTTP Response from "http://jf.knarcraft.net/videos/b77f777a-1b13-844a-bce9-90d68876fb6e/live.m3u8?DeviceId=TW96aWxsYS81LjAgKFgxMTsgTGludXggeDg2XzY0OyBydjo5MS4wKSBHZWNrby8yMDEwMDEwMSBGaXJlZm94LzkxLjB8MTY1MTY2MjgwODEwMA11&MediaSourceId=b77f777a1b13844abce990d68876fb6e&VideoCodec=h264&AudioCodec=aac,mp3&VideoBitrate=2808000&AudioBitrate=192000&PlaySessionId=da66f3a7eb6b48be9ad0b03c81569df4&api_key=5857d29d35274efbb169a002e774e72c&TranscodingMaxAudioChannels=6&RequireAvc=false&Tag=66a64b37817d2d099b3222d84129629f&SegmentContainer=ts&MinSegments=1&BreakOnNonKeyFrames=True&h264-profile=high,main,baseline,constrainedbaseline&h264-level=51&h264-deinterlace=true&TranscodeReasons=ContainerNotSupported,ContainerBitrateExceedsLimit&allowVideoStreamCopy=false" to "192.168.200.112" in 0:00:02.9131269 with Status Code 200
[2022-05-04 15:19:45.693 +02:00] [INF] GetPostedPlaybackInfo profile: DeviceProfile { Name: null, Id: null, Identification: null, FriendlyName: null, Manufacturer: null, ManufacturerUrl: null, ModelName: null, ModelDescription: null, ModelNumber: null, ModelUrl: null, SerialNumber: null, EnableAlbumArtInDidl: False, EnableSingleAlbumArtLimit: False, EnableSingleSubtitleLimit: False, SupportedMediaTypes: "Audio,Photo,Video", UserId: null, AlbumArtPn: null, MaxAlbumArtWidth: 0, MaxAlbumArtHeight: 0, MaxIconWidth: null, MaxIconHeight: null, MaxStreamingBitrate: 120000000, MaxStaticBitrate: 100000000, MusicStreamingTranscodingBitrate: 384000, MaxStaticMusicBitrate: null, SonyAggregationFlags: null, ProtocolInfo: null, TimelineOffsetSeconds: 0, RequiresPlainVideoItems: False, RequiresPlainFolders: False, EnableMSMediaReceiverRegistrar: False, IgnoreTranscodeByteRangeRequests: False, XmlRootAttributes: [], DirectPlayProfiles: [DirectPlayProfile { Container: "webm", AudioCodec: "vorbis,opus", VideoCodec: "vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "mp4,m4v", AudioCodec: "aac,mp3,opus,flac,vorbis", VideoCodec: "h264,vp8,vp9,av1", Type: Video }, DirectPlayProfile { Container: "opus", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "opus", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "mp3", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "aac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4a", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "m4b", AudioCodec: "aac", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "flac", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webma", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "webm", AudioCodec: "webma", VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "wav", AudioCodec: null, VideoCodec: null, Type: Audio }, DirectPlayProfile { Container: "ogg", AudioCodec: null, VideoCodec: null, Type: Audio }], TranscodingProfiles: [TranscodingProfile { Container: "ts", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "opus", Type: Audio, VideoCodec: null, AudioCodec: "opus", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp3", Type: Audio, VideoCodec: null, AudioCodec: "mp3", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "aac", Type: Audio, VideoCodec: null, AudioCodec: "aac", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "wav", Type: Audio, VideoCodec: null, AudioCodec: "wav", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "ts", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3", Protocol: "hls", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 1, SegmentLength: 0, BreakOnNonKeyFrames: True }, TranscodingProfile { Container: "webm", Type: Video, VideoCodec: "vpx", AudioCodec: "vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Streaming, EnableSubtitlesInManifest: False, MaxAudioChannels: "6", MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }, TranscodingProfile { Container: "mp4", Type: Video, VideoCodec: "h264", AudioCodec: "aac,mp3,opus,flac,vorbis", Protocol: "http", EstimateContentLength: False, EnableMpegtsM2TsMode: False, TranscodeSeekInfo: Auto, CopyTimestamps: False, Context: Static, EnableSubtitlesInManifest: False, MaxAudioChannels: null, MinSegments: 0, SegmentLength: 0, BreakOnNonKeyFrames: False }], ContainerProfiles: [], CodecProfiles: [CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: "aac", Container: null }, CodecProfile { Type: VideoAudio, Conditions: [ProfileCondition { Condition: Equals, Property: IsSecondaryAudio, Value: "false", IsRequired: False }], ApplyConditions: [], Codec: null, Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "high|main|baseline|constrained baseline", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "51", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "h264", Container: null }, CodecProfile { Type: Video, Conditions: [ProfileCondition { Condition: NotEquals, Property: IsAnamorphic, Value: "true", IsRequired: False }, ProfileCondition { Condition: EqualsAny, Property: VideoProfile, Value: "main", IsRequired: False }, ProfileCondition { Condition: LessThanEqual, Property: VideoLevel, Value: "120", IsRequired: False }, ProfileCondition { Condition: NotEquals, Property: IsInterlaced, Value: "true", IsRequired: False }], ApplyConditions: [], Codec: "hevc", Container: null }], ResponseProfiles: [ResponseProfile { Container: "m4v", AudioCodec: null, VideoCodec: null, Type: Video, OrgPn: null, MimeType: "video/mp4", Conditions: [] }], SubtitleProfiles: [SubtitleProfile { Format: "vtt", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ass", Method: External, DidlMode: null, Language: null, Container: null }, SubtitleProfile { Format: "ssa", Method: External, DidlMode: null, Language: null, Container: null }] }
[2022-05-04 15:19:45.736 +02:00] [ERR] Error in "ffprobe"
System.Text.Json.JsonException: The JSON value could not be converted to System.Int32. Path: $.chapters[0].id | LineNumber: 470 | BytePositionInLine: 38.
 ---> System.FormatException: Either the JSON value is not in a supported format, or is out of bounds for an Int32.
   at System.Text.Json.Utf8JsonReader.GetInt32()
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TCollection& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
```

**Additional Context**

If relevant, here is the apt upgrade info:
```Start-Date: 2022-05-04  02:58:48
Commandline: apt upgrade
Requested-By: kristian (1000)
Upgrade: jellyfin-ffmpeg:amd64 (4.4.1-4-bullseye, 5.0.1-1-bullseye), openjdk-17-jdk:amd64 (17.0.2+8-1~deb11u1, 17.0.3+7-1~deb11u1), openjdk-17-jre:amd64 (17.0.2+8-1~deb11u1, 17.0.3+7-1~deb11u1), openjdk-17-jdk-headless:amd64 (17.0.2+8-1~deb11u1, 17.0.3+7-1~deb11u1), openjdk-17-jre-headless:amd64 (17.0.2+8-1~deb11u1, 17.0.3+7-1~deb11u1)
End-Date: 2022-05-04  02:59:06

Start-Date: 2022-05-04  12:30:47
Commandline: apt upgrade
Requested-By: kristian (1000)
Upgrade: jellyfin-ffmpeg:amd64 (5.0.1-1-bullseye, 5.0.1-2-bullseye)
End-Date: 2022-05-04  12:30:52
```

**Comment by Shadowghost** [comment]
This was fixed in 10.8 by https://github.com/jellyfin/jellyfin/pull/7363

I guess you need to downgrade ffmpeg to make it work properly with 10.7.7...

**Comment by EpicKnarvik97** [comment]
> This was fixed in 10.8 by [jellyfin/jellyfin#7363](https://github.com/jellyfin/jellyfin/pull/7363)
> 
> I guess you need to downgrade ffmpeg to make it work properly with 10.7.7...

```
sudo apt install jellyfin-ffmpeg=4.4.1-4
Leser pakkelister ... Ferdig
Skaper oversikt over avhengighetsforhold ... Ferdig
Leser tilstandsinformasjon ... Ferdig              
E: Versjon «4.4.1-4» av «jellyfin-ffmpeg» ble ikke funnet
```
```
sudo apt install jellyfin-ffmpeg=4.4.1-4-bullseye
[sudo] passord for kristian: 
Leser pakkelister ... Ferdig
Skaper oversikt over avhengighetsforhold ... Ferdig
Leser tilstandsinformasjon ... Ferdig              
E: Versjon «4.4.1-4-bullseye» av «jellyfin-ffmpeg» ble ikke funnet
```

Apt says the previous version is not found. It might be that I'm not allowed to downgrade as it's considered a security update. Or is there another trivial way of downgrading I'm unaware of?

**Comment by Shadowghost** [comment]
The repo is currently being restored to provide 4.4.1-4 again.

**Comment by joshuaboniface** [comment]
You should be able to `apt update` and then `apt install --reinstall jellyfin-ffmpeg` to restore back to 4.4.

**Comment by EpicKnarvik97** [comment]
> You should be able to `apt update` and then `apt install --reinstall jellyfin-ffmpeg` to restore back to 4.4.

```
sudo apt install --reinstall jellyfin-ffmpeg
Leser pakkelister ... Ferdig
Skaper oversikt over avhengighetsforhold ... Ferdig
Leser tilstandsinformasjon ... Ferdig              
0 oppgraderte, 0 nylig installerte, 1 installert på nytt, 0 å fjerne og 0 ikke oppgradert.
Må hente 36,2 MB med arkiver.
Etter denne operasjonen vil 0 B ekstra diskplass bli brukt.
Feil:1 https://repo.jellyfin.org/debian bullseye/main amd64 jellyfin-ffmpeg amd64 5.0.1-2-bullseye
  404  Not Found [IP: 68.183.204.194 443]
E: Klarte ikke å skaffe https://repo.jellyfin.org/debian/pool/main/j/jellyfin-ffmpeg/jellyfin-ffmpeg_5.0.1-2-bullseye_amd64.deb  404  Not Found [IP: 68.183.204.194 443]
E: Klarte ikke å hente alle arkivene. Du kan prøve med «apt-get update» eller «--fix-missing».
```

Hmm. I'm getting a 404 error now for some reason.

**Comment by Shadowghost** [comment]
You might need to uninstall and reinstall because your local version is tried to be reinstalled (which is still 5.0.1-2).

**Comment by EpicKnarvik97** [comment]
After uninstalling jellyfin-ffmpeg which caused the uninstallation of the jellyfin package, it still cannot find jellyfin-ffmpeg=4.4.1-4. When trying to install either jellyfin or jellyfin-ffmpeg again, I get the same 404 error.

**Comment by EpicKnarvik97** [comment]
Actually, it seems that removing jellyfin-ffmpeg makes it default to the native ffmpeg installation which does not cause the same error.

**Comment by Shadowghost** [comment]
Manually delete the cached lists in `/var/lib/apt/lists`, run ` apt-get update` and install afterwards again. Worked for me.

**Comment by EpicKnarvik97** [comment]
> Manually delete the cached lists in `/var/lib/apt/lists`, run ` apt-get update` and install afterwards again. Worked for me.

Removing the cached lists fixed the version stuff and allowed me to download 4.4.1-4
