### ISSUE TITLE
ffmpeg/ffprobe long path problem on windows

### ISSUE THREAD

**Issue by azuse** [jellyfin/jellyfin-ffmpeg#145]
**Describe The Bug**
Windows has a legacy problem on MAX_PATH exceeding 260 characters. Modern windows has mostly solved the problem (so does jellyfin itself) , but ffmpeg hadn't fixed the problem until a patch in April. 
Unfortunately, the ffpmeg used by jellyfin still has this problem.

The patch fixed this problem is listed here: https://github.com/yt-dlp/FFmpeg-Builds#1-long-path-support-for-windows
It also provide a release which I test ok to replace the ffmpeg/ffprobe come with jellyfin and easy fix the problem.
The patch itself including following code changes:

```
[[FFmpeg-devel] [PATCH v11 1/6] libavutil/wchar_filename.h: Add whcartoutf8, wchartoansi and utf8toansi ](https://ffmpeg.org/pipermail/ffmpeg-devel/2022-April/295569.html)  Nil Admirari
[[FFmpeg-devel] [PATCH v11 2/6] libavformat/avisynth.c: Remove MAX_PATH limit ](https://ffmpeg.org/pipermail/ffmpeg-devel/2022-April/295567.html)  Nil Admirari
[[FFmpeg-devel] [PATCH v11 3/6] compat/w32dlfcn.h: Remove MAX_PATH limit and replace LoadLibraryExA with LoadLibraryExW ](https://ffmpeg.org/pipermail/ffmpeg-devel/2022-April/295570.html)  Nil Admirari
[[FFmpeg-devel] [PATCH v11 4/6] fftools/cmdutils.c: Remove MAX_PATH limit ](https://ffmpeg.org/pipermail/ffmpeg-devel/2022-April/295568.html)  Nil Admirari
[[FFmpeg-devel] [PATCH v11 5/6] fftools: Enable long path support on Windows (fixes #8885) ](https://ffmpeg.org/pipermail/ffmpeg-devel/2022-April/295571.html)  Nil Admirari
[[FFmpeg-devel] [PATCH v11 6/6] fftools: Set active code page to UTF-8 on Windows ](https://ffmpeg.org/pipermail/ffmpeg-devel/2022-April/295572.html)  Nil Admirari 
```

**Steps To Reproduce**
Have a file placed in extrem long path (you can see an example in error message below), try to play it with jellyfin or call ffprobe directly, would end with a ffprobe file not exist error.

**System (please complete the following information):**

- **Platform:** [e.g. Linux, Windows]
- **Operating System:** Windows 10 Build 21H2
- **Virtualization**: No
- **Jellyfin Version:** 10.8.0
- **Jellyfin-FFmpeg Version:** included in 10.8.0
- **Hardware Acceleration:** Nvidia
- **CPU & GPU Model**: i9-10850k RTX3080TI

**FFmpeg Logs**
ffprobe log:
```
[2022-05-11 10:00:11.544 +08:00] [ERR] [82] MediaBrowser.Controller.Entities.BaseItem: Error refreshing owned items for "Y:\[DVDISO][アニメ][140207] 夜桜四重奏 ツキニナク OAD 第02話 ｢コミック15巻限定版DVD｣ (iso+mds)\Exra\Menu OAD (Vol.2).VOB"
System.IO.DirectoryNotFoundException: Could not find a part of the path 'Y:\[DVDISO][アニメ][140207] 夜桜四重奏 ツキニナク OAD 第02話 ｢コミック15巻限定版DVD｣ (iso+mds)\Exra'.
   at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
   at System.IO.Enumeration.FileSystemEnumerator`1.Init()
   at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
   at System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(String directory, String expression, EnumerationOptions options, Boolean isNormalized)
   at System.IO.DirectoryInfo.InternalEnumerateInfos(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
   at Emby.Server.Implementations.IO.ManagedFileSystem.GetFileSystemEntries(String path, Boolean recursive)
   at MediaBrowser.Controller.Providers.DirectoryService.<>c.<GetFileSystemEntries>b__5_0(String p, IFileSystem fileSystem)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd[TArg](TKey key, Func`3 valueFactory, TArg factoryArgument)
   at MediaBrowser.Controller.Providers.DirectoryService.GetFileSystemEntries(String path)
   at MediaBrowser.Controller.Entities.BaseItem.RefreshMetadata(MetadataRefreshOptions options, CancellationToken cancellationToken)
[2022-05-11 10:00:11.565 +08:00] [ERR] [81] MediaBrowser.Providers.Movies.MovieMetadataService: Error in "ffprobe"
```
You can also see this problem in this test of two files which one has a name exceeding max path limit and the other not.
![](http://azusebox.moe/wp-content/uploads/2022/05/ffprobe-folder.png)
![](http://azusebox.moe/wp-content/uploads/2022/05/ffprobe-test.jpg)

**Additional Context**

**Comment by nyanmisaka** [comment]
Thanks for the info, I’ll look into it.

**Comment by nyanmisaka** [comment]
Relevant patches are added in #146. You can install from the workflow artifacts before we making a new release for it.

And FYI jellyfin-ffmpeg is always recommend if you use hardware acceleration.
